src-d/lookout-sdk

.travis.yml, MAINTAINERS, _tools/install-lookout-latest.sh
=> lookout-sdk binary

.travis.yml, Makefile, _tools/install-lookout-latest.sh, python/setup.py
Following https://github.com/bblfsh/client-python/pull/110
This resolves CI failures from [master](https://travis-ci.org/src-d/lookout-sdk/jobs/429940471) and #10 ([log](https://travis-ci.org/src-d/lookout-sdk/jobs/429940471))
- fix grpcio version
- make sdk binary installation more robust
=> CI: fix grpcio version

pb/event.go
Needed by https://github.com/src-d/lookout/issues/259
this change doesn't break api because ID methods exists only in go and currently only lookout server uses it.
=> change id of review event

.gitignore, .travis.yml, Makefile, _tools/install-lookout-latest.sh, _tools/install-protoc-maybe.sh, _tools/protogen_golang.sh
Doing `make protogen` I faced some problems, and it took me a while to realize the problem because the bash scripts are downloading things in the project's parent dir.
In my opinion we should either use the current dir, or tmp. In this PR:
- downloads are made on the current dir, not the parent.
- `make protogen` uses `pip3 --user` to make it more user-friendly.
=> Use current dir for tool downloads

.travis.yml
Tests are failing in master because we use this repo for the tests, and the default clone depth of 50 finally left out the commits we use.
Context:
https://travis-ci.org/src-d/lookout-sdk/jobs/445009718#L747
https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
=> Remove git clone depth in Travis

.travis.yml, language-analyzer.py, python/setup.py
Includes the commit from #19.
The linter ignores the autogenerated code, and sets the line length to 99, as defined in [our guide](https://github.com/src-d/guide/blob/master/engineering/conventions-python.md).
=> Add a linter for python pep8 style

pb/event.go, pb/event_test.go
we need to support file schema too.
we use it in lookout-sdk binary.
=> allow file schema for repositories

pb/struct.go, pb/struct_test.go
move `ToStruct` methods from lookout to sdk.
It's easy to work with protobuf structs in other languages, for example [python](https://developers.google.com/protocol-buffers/docs/reference/python-generated#struct). But a lot of pain in go.
Analyzers need this method for unit testing.
=> add ToStruct method to go sdk

README.md, language-analyzer.go, pb/grpc.go
Move low-level gRPC helpers from lookout to sdk.
Currently, URI schema is a huge mess. Some analyzers support RFC 3986 others not. Infra suffered from it already. This PR brings helpers to sdk and mention them as best-practice.
We allow to change `maxMessageSize` in lookoutd but it doesn't make much sense to have increased size only on server or client side. Better if they always match.
Similar helpers are implemented in python by https://github.com/src-d/lookout-sdk/pull/37.
=> Add grpc helpers to go

README.md, language-analyzer.py, python/lookout/__init__.py, python/lookout/sdk/__init__.py, python/lookout/sdk/grpc.py
Based on #35 (because of README.md conflicts)
Only 2 new commits:
1. Changes in code [8259fc614d1d7cb0ab15218dc5e96e0170874c6e](https://github.com/src-d/lookout-sdk/commit/8259fc614d1d7cb0ab15218dc5e96e0170874c6e)
2. Changes in documentation [8af42e5a2ca02cad1c9f33dd6a95df2f5776f836](https://github.com/src-d/lookout-sdk/commit/8af42e5a2ca02cad1c9f33dd6a95df2f5776f836)
=> Add grpc helpers to python

.travis.yml, _tools/ci-run-bblfsh.sh, language-analyzer.go
Fix: #31
- make ci faster
- fix lack of output for python analyzer
- add checks for error
- add unit tests run
- add bblfsh (both analyzers depend on it)
- fix for golang example analyzer (panic)
=> actually test analyzers in ci

language-analyzer.py, python/lookout/sdk/__init__.py, python/lookout/sdk/pb.py
Superseded #39
The first commit has the same change but correct commit message with the explanation why we need it.
The second re-export grpc stuff as we agreed in a comment to that PR.
=> Remove grpc imports from init and add pb package

Makefile, _tools/install-gogofaster-maybe.sh, _tools/install-protoc-maybe.sh, _tools/protogen_golang.sh, pb/event.pb.go, pb/service_analyzer.pb.go, pb/service_data.pb.go
This PR would fix the issue with code generation in go, caused by a [new release](https://github.com/gogo/protobuf/releases) of `gogo/protobuf-v1.2.0`.
Because of that, Travis is failing: https://travis-ci.org/src-d/lookout-sdk/jobs/465002703
```
-	IncludeLanguages []string `protobuf:"bytes,8,rep,name=include_languages,json=includeLanguages" json:"include_languages,omitempty"`
+	IncludeLanguages []string `protobuf:"bytes,8,rep,name=include_languages,json=includeLanguages,proto3" json:"include_languages,omitempty"`
```
This PR will lock our code generation to the new `gogofaster v1.2.0`.
It builds `protoc-gen-gogofaster` from release `gogo/protobuf-v1.2.0` and uses it without messing user binaries nor sources.
- we should update `lookout` to depend on the new `protobuf v1.2.0` (it …
=> Lock gogofaster to a fixed v1.2.0

python/setup.py
Locked version is causing error when an application needs to use newer
compatible grpcio.
Ref: https://github.com/bblfsh/client-python/pull/138
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> Use version range for grpcio instead of exact version

python/lookout/__init__.py
The warning does not apply anymore, since the code is not auto-generated since #55 was merged.
=> Remove outdated warning in python init file

Makefile, docs/CONTRIBUTING.md
I guess the `make godep` comes from copy&paste from lookout, but we don't use it here. Same for the TOC, it was removed during docs reviews.
=> Remove outdated steps from docs

README.md, examples/language-analyzer.go, pb/grpc.go
Fix: #52
Python already open insecure connection by default: https://github.com/src-d/lookout-sdk/blob/master/python/lookout/sdk/grpc.py#L13
Go updated.
Doc for python `add_insecure_port` was placed in a wrong place in README (it has nothing to do with data server)
=> Insecure connection by default

README.md
Ref: https://github.com/src-d/lookout-sdk/issues/64
=> Mention caveat and fix for connections to data-server in golang

.travis.yml
If you try to install lookout-sdk using pip with non-default
installation options, it will disable wheels and the installation will
fail.
Example:
```
$ pip3 install --install-option="--prefix=/install" lookout==0.3.0
/usr/local/lib/python3.6/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
cmdoptions.check_install_build_global(options)
Collecting lookout==0.3.0
Cache entry deserialization failed, entry ignored
Could not find a version that satisfies the requirement lookout==0.3.0 (from versions: 0.0.1)
No matching distribution found for lookout==0.3.0
```
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> publish python sdk as sdist too

.travis.yml
Fix #69.
Apparently `3.6` is not available in the travis image anymore, this PR sets it to `3.6.7`. Using a patch version probably means that this will break again soon, but I don't see how to fix it right now.
```
$ pyenv versions
system
2.7.15
* 3.6.7 (set by PYENV_VERSION environment variable)
3.7
3.7.1
```
=> Set pyenv version 3.6.7 in travis.yml

README.md
[FailFast is now deprecated](https://github.com/grpc/grpc-go/releases/tag/v1.18.0), and the recommended method is WaitForReady.
=> Replace grpc FailFast with WaitForReady

pb/grpc.go, pb/grpc_test.go
Part of #84.
While migrating lookout I noticed that we can't use `pb.AddFields` inside a client interceptor. This is because `pb.DialContextWithInterceptors` was executing `Ctxlog*ClientInterceptor` before the user provided ones.
With the change in this PR the interceptors are called in this order:
```
user client interceptors -> lookout-sdk client Ctxlog interceptor -> ...gRPC call...
-> lookout-sdk server Ctxlog interceptor -> user server interceptors
```
Instead of the previous one:
```
lookout-sdk client Ctxlog interceptor -> user client interceptors -> ...gRPC call...
-> lookout-sdk server Ctxlog interceptor -> user server interceptors
```
@se7entyse7en can you please check if we can have a similar problem in the python API?
=> Change Go interceptors order
